version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: power_consumption
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  esp32-simulator:
    build: ./esp32_simulator
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: power_consumption
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "5000:5000"
    volumes:
      - ./esp32_simulator/data:/app/data

  nilm-predictor:
    build: ./nilm_predictor
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: power_consumption
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - ./nilm_predictor/model:/app/model
    command: python prediction.py

  flask-api:
    build: ./flask_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: power_consumption
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "5001:5001"
    volumes:
      - ./flask_api:/app

volumes:
  postgres-data: